#!/usr/bin/env python3

import sys
import numpy

def sort(list):
	sortList = list
	return sortList

def parcours(list):
	sortList = sort(list)
	print(sortList)

def main():
	list = numpy.random.normal(0,1000,1000).tolist()
	parcours(list)
	sys.exit(0)



main()
